version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: taxi-app-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@shopper
      POSTGRES_DB: taxiappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: